rtl/core/lpu_pkg.sv
rtl/core/lpu_isa_decode.sv
rtl/core/lpu_stream_stage.sv
rtl/core/lpu_control_pipeline.sv
rtl/icu/lpu_icu_queue.sv
rtl/icu/lpu_icu.sv
rtl/mem/lpu_sram_1rw_banked.sv
rtl/mem/lpu_mem_tile_slice.sv
rtl/mem/lpu_mem_tile_slice_sram.sv
rtl/mem/lpu_mem_tile_slice_select.sv
rtl/mem/lpu_mem_column.sv
rtl/mem/lpu_mem_hemisphere.sv
rtl/vxm/lpu_vxm_math_pkg.sv
rtl/mxm/lpu_mxm_control.sv
rtl/mxm/lpu_mxm_dequantizer.sv
rtl/mxm/lpu_mxm_weight_buffer.sv
rtl/mxm/lpu_mxm_dot_bank.sv
rtl/mxm/lpu_mxm_compute.sv
rtl/mxm/lpu_mxm_accumulator_sram.sv
rtl/mxm/lpu_mxm_shared_accumulator.sv
rtl/mxm/lpu_mxm_accumulator.sv
rtl/mxm/lpu_mxm_block_accumulator.sv
rtl/mxm/lpu_mxm_slice.sv
rtl/sxm/lpu_sxm_control.sv
rtl/sxm/lpu_sxm_slice.sv
rtl/vxm/lpu_vxm_control.sv
rtl/vxm/lpu_vxm_alu.sv
rtl/vxm/lpu_vxm_execute.sv
rtl/vxm/lpu_vxm_result_packer.sv
rtl/vxm/lpu_vxm_stream_bridge.sv
rtl/vxm/lpu_vxm_slice.sv
rtl/lpu_top.sv
sim/tb/lpu_smoke_tb.sv
sim/tb/lpu_arch_tb.sv
sim/tb/lpu_mem_stream_tb.sv
sim/tb/lpu_sxm_transpose_tb.sv
sim/tb/lpu_sxm_wavefront_tb.sv
sim/tb/lpu_vxm_int8_tb.sv
sim/tb/lpu_vxm_fp16_tb.sv
sim/tb/lpu_vxm_fp32_arithmetic_tb.sv
sim/tb/lpu_mxm_vector_tb.sv
sim/tb/lpu_mxm_fault_tb.sv
sim/tb/lpu_mxm_accumulator_tb.sv
sim/tb/lpu_mxm_column_tb.sv
sim/tb/lpu_mxm_int8_dequant_tb.sv
sim/tb/lpu_mxm_block8_tb.sv
sim/tb/lpu_mxm_weight_stream_tb.sv
sim/tb/lpu_smollm2_ffn_tb.sv
